/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StatisticsImport } from './routes/statistics'
import { Route as StakingImport } from './routes/staking'
import { Route as IndexImport } from './routes/index'
import { Route as DynamicIndexImport } from './routes/dynamic/index'
import { Route as ConservativeIndexImport } from './routes/conservative/index'

// Create/Update Routes

const StatisticsRoute = StatisticsImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRoute,
} as any)

const StakingRoute = StakingImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DynamicIndexRoute = DynamicIndexImport.update({
  id: '/dynamic/',
  path: '/dynamic/',
  getParentRoute: () => rootRoute,
} as any)

const ConservativeIndexRoute = ConservativeIndexImport.update({
  id: '/conservative/',
  path: '/conservative/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingImport
      parentRoute: typeof rootRoute
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsImport
      parentRoute: typeof rootRoute
    }
    '/conservative/': {
      id: '/conservative/'
      path: '/conservative'
      fullPath: '/conservative'
      preLoaderRoute: typeof ConservativeIndexImport
      parentRoute: typeof rootRoute
    }
    '/dynamic/': {
      id: '/dynamic/'
      path: '/dynamic'
      fullPath: '/dynamic'
      preLoaderRoute: typeof DynamicIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/staking': typeof StakingRoute
  '/statistics': typeof StatisticsRoute
  '/conservative': typeof ConservativeIndexRoute
  '/dynamic': typeof DynamicIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staking': typeof StakingRoute
  '/statistics': typeof StatisticsRoute
  '/conservative': typeof ConservativeIndexRoute
  '/dynamic': typeof DynamicIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/staking': typeof StakingRoute
  '/statistics': typeof StatisticsRoute
  '/conservative/': typeof ConservativeIndexRoute
  '/dynamic/': typeof DynamicIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/staking' | '/statistics' | '/conservative' | '/dynamic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/staking' | '/statistics' | '/conservative' | '/dynamic'
  id:
    | '__root__'
    | '/'
    | '/staking'
    | '/statistics'
    | '/conservative/'
    | '/dynamic/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StakingRoute: typeof StakingRoute
  StatisticsRoute: typeof StatisticsRoute
  ConservativeIndexRoute: typeof ConservativeIndexRoute
  DynamicIndexRoute: typeof DynamicIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StakingRoute: StakingRoute,
  StatisticsRoute: StatisticsRoute,
  ConservativeIndexRoute: ConservativeIndexRoute,
  DynamicIndexRoute: DynamicIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/staking",
        "/statistics",
        "/conservative/",
        "/dynamic/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/staking": {
      "filePath": "staking.tsx"
    },
    "/statistics": {
      "filePath": "statistics.tsx"
    },
    "/conservative/": {
      "filePath": "conservative/index.tsx"
    },
    "/dynamic/": {
      "filePath": "dynamic/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
